# Generated by Django 3.0.5 on 2021-03-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('eno', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=255)),
                ('elocation', models.CharField(max_length=255)),
                ('edate', models.DateField()),
                ('etime', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
