# Generated by Django 3.0.5 on 2021-03-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
