# Generated by Django 3.0.5 on 2021-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antpage', '0002_auto_20210326_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
