# Generated by Django 3.0.5 on 2021-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antpage', '0007_auto_20210326_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
