# Generated by Django 3.0.5 on 2021-03-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antpage', '0009_auto_20210326_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
